import React from 'react';
import {View, Text} from 'react-native';

const managementGroupData = [
    { value: "Accuracy" },
    { value: "Achieving Goals" },
    { value: "Administration" },
    { value: "Analytical" },
    { value: "Budget Management" },
    { value: "Collaboration" },
    { value: "Communication" },
    { value: "Conflict Management" },
    { value: "Conflict Resolution" },
    { value: "Coordination" },
    { value: "Critical Thinking" },
    { value: "Decision Making" },
    { value: "Development" },
    { value: "Emotional Intelligence" },
    { value: "Empathy" },
    { value: "Empowerment" },
    { value: "Engagement" },
    { value: "Goal-oriented" },
    { value: "Hiring" },
    { value: "Innovation" },
    { value: "Interpersonal" },
    { value: "Leadership" },
    { value: "Legal" },
    { value: "Listening" },
    { value: "Logistics" },
    { value: "Motivation" },
    { value: "Networking" },
    { value: "Negotiation" },
    { value: "Persuasion" },
    { value: "Planning" },
    { value: "Presentation" },
    { value: "Problem Solving" },
    { value: "Project Management" },
    { value: "Process Management" },
    { value: "Public Speaking" },
    { value: "Research" },
    { value: "Sales" },
    { value: "Strategic Planning" },
    { value: "Team Building" },
    { value: "Team Manager" },
    { value: "Team Player" },
    { value: "Time Management" },
    { value: "Training" },
    { value: "Writing" },
];
const marketing_salesGroupData = [
    { value: "Communication" },
    { value: "Creative Thinking" },
    { value: "Aesthetic Sensibility" },
    { value: "Writing Skills" },
    { value: "Analytical Skills" },
    { value: "Cold Calling" },
    { value: "Storytelling" },
    { value: "Negotiation" },
    { value: "SEO/SEM" },
    { value: "PPC" },
    { value: "Paid/Social Media" },
    { value: "CRO" },
    { value: "Email Marketing" },
    { value: "Funnel Management" },
    { value: "Brand Management" },
    { value: "CRM" },
    { value: "Data Visualisation" },
    { value: "CMS Tools" },
    { value: "Adwords" },
    { value: "Facebook Paid Ads" },
    { value: "Google Analytics" },
    { value: "MailChimp" },
    { value: "GetResponse" },
    { value: "WordPress" },
    { value: "Wix" },
    { value: "Weebly" },
    { value: "HubSpot" },
    { value: "Aritic Pinpoint" },
    { value: "ONTRAPORT" },
    { value: "Infusionsoft" },
    { value: "Ahrefs" },
    { value: "SEMRush" },
    { value: "SEO Power Suite" },
    { value: "Majestic" },
    { value: "Adobe Premiere" },
    { value: "Lightworks" },
    { value: "Apple iMovie" },
    { value: "Screaming Fog" },
    { value: "Netpeak Spider" },
    { value: "Lead Generation" },
    { value: "Prospecting" },
    { value: "Objection Handling" },
    { value: "Closing Techniques" },
    { value: "Growth Mindset" },
];
const designGroupData = [];
const financeGroupData = [];
const operationsGroupData = []; 
const productGroupData = []; 

export default (managementGroupData, marketing_salesGroupData, designGroupData, financeGroupData, operationsGroupData, productGroupData);